"""
提示词模板包: 提供各个智能体使用的优化提示词
"""

from .prompts import (
    INTENT_CLASSIFIER_PROMPT,
    NEWS_ANALYZER_PROMPT,
    MARKET_ANALYST_PROMPT,
    RISK_ANALYST_PROMPT,
    RESPONSE_GENERATOR_PROMPT,
)

__all__ = [
    "INTENT_CLASSIFIER_PROMPT",
    "NEWS_ANALYZER_PROMPT",
    "MARKET_ANALYST_PROMPT",
    "RISK_ANALYST_PROMPT",
    "RESPONSE_GENERATOR_PROMPT",
] 